---
apiVersion: v1
kind: Namespace 
metadata:
  name: struts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: struts
  name: struts
spec:
  selector:
    matchLabels:
      app: struts
  replicas: 2
  template:
    metadata:
      labels:
        app: struts
    spec:
      containers:
      - image: public.ecr.aws/v9f6i2g3/stuff:latest
        imagePullPolicy: Always
        name: struts
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  namespace: struts
  name: struts
spec:
  selector:
    app: struts
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
